# Server Port (React aasaani se connect kar payega)
server.port=8080

# Naye Database ka Connection (Humne naam rakha hai: showbox_java_db)
# createDatabaseIfNotExist=true apne aap naya DB bana dega!
spring.datasource.url=jdbc:mysql://localhost:3306/showbox_java_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nishchay1450#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Ye aapki C# Entity Framework ki tarah kaam karega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email settings (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nishchaybenke@gmail.com
spring.mail.password=igrsotbkqdessypr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true